#!/bin/bash -x

########## Utilitar captura ##########
# Autori 
# calvarr: https://github.com/calvarr
# bionel: https://github.com/bionel
# Licenta: nu am stabilit inca
######################################

master=bionel

actualizare (){
commit1=` wget -qO - https://github.com/$master/captura-cli/commits/master|grep sha|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}'`
if [ ! -f $HOME/captura-cli/commit ];then 
wget -qO - https://github.com/$master/captura-cli/commits/master|grep sha|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}' > $HOME/captura-cli/commit
else
commit2=`cat $HOME/captura-cli/commit|sed -n '$p'`
fi
if [[ "$commit1" != "$commit2" ]]; then 
wget -qO - https://github.com/$master/captura-cli/commits/master|grep sha|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}' > $HOME/captura-cli/commit
echo 'NU UITA SA FACI "git pull"!'
wget -qO - https://github.com/$master/captura-cli/commits/master|grep '"message">'|sed 's/<[^>]*>/ /g'|sed '2,$d'
fi
}

#actualizare

######## Valori predefinite ##########

# daca ati creat fisierul .dialogrc personalizat in directorul in care
# aveti scriptul, activati linia de mai jos ↓
#export DIALOGRC=./.dialogrc 

# procesare: ffmpeg sau avconv
export procesare=ffmpeg
export stream_server=ffserver
export data=`date +%y%m%d%H%M%S`

# alegeti playerul dorit: mplayer, cvlc, vlc etc.
# implicit: mplayer
export v_player=mplayer

# directorul in care se salveaza captura
if [ ! -d "$HOME/capturi" ]; then
 mkdir $HOME/capturi
fi
export dir_salvare=$HOME/capturi

# rezolutie maxima desktop
export desktop=`grep -i "initial mode" /var/log/Xorg.0.log|sed -n '2p'|awk '{print $NF}'`

# rezolutie camera web
export cam_web=640x480

########### Initializari ##############

test_tty=`echo $DISPLAY X|awk '{print $2}'`

if [[ "$test_tty" = "X" ]];then
  if [ `builtin type -p xdialog` ];then DIALOG=xdialog
    elif [ `builtin type -p Xdialog` ];then DIALOG=Xdialog
    elif [ `builtin type -p gdialog` ];then DIALOG=gdialog
    elif [ `builtin type -p kdialog` ];then DIALOG=kdialog
  else
  DIALOG=dialog
  fi
else
  DIALOG=dialog
fi

#fortare DIALOG pt teste in consola
#DIALOG=dialog

export DIALOG

########## MENIU PRINCIPAL ###########

tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/capclitmp$$
export tempfile

# functie de siguranta pentru stergere fisiere temporare
# in caz de iesire anormala, ex: Ctrl-C
trap "rm -f $tempfile" 0 1 2 5 15

until [ "$selectie0" == "1" ]; do

  $DIALOG --backtitle "Utilitar captura v. foarte alfa" \
	  --title "Varianta calvarr/bionel" --clear \
          --menu "Meniu Principal:" 20 80 10 \
   "01" "Configurare" \
   "02" "Captura" \
   "03" "Redare" \
   "04" "Streaming" \
   "10" "Paraseste programul"  2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`
  
  case "$selectat" in
    01) ./configurare;;
    02) ./captura;;
    03) ./redare;;
    04) ./streaming;;
    05) echo "Cuuui ma laasi?!! ( opt. $selectat )"
       echo "desktop=$desktop"
       echo "test_tty=$test_tty"
       echo "DIALOG=$DIALOG"
       exit 0 ;;
  esac

  if [ "$selectie0" == "255" ]; then
   echo "Exit by ESC!"
   exit 0
  fi

done

#pt. debug
echo "Exit by done (Cancel)!"
echo "desktop=$desktop"
echo "test_tty=$test_tty"
echo "Dialog=$DIALOG"

