#!/bin/bash

tempfile2=/tmp/capclitmp2
trap "rm -f $tempfile2" 0 1 2 5 15
capturi=`ls $HOME/capturi|nl`
      $DIALOG  --title "Redare" --clear \
               --menu "Selectati captura dorita :" 20 80 10  $capturi 2> $tempfile2
      selectie2=$?
s_captura=`cat $tempfile2`
captura=`ls $HOME/capturi|sed -n "${s_captura}p"`
echo captura $captura #debug
$v_player $HOME/capturi/$captura
