#!/bin/bash


until [ "$selectie0" == "1" ]; do

  $DIALOG --backtitle "Streaming" \
	  --title "Varianta calvarr/bionel" --clear \
          --menu "Meniu Principal:" 20 80 10 \
   "01" "Stream Webcam" \
   "02" "Stream Webcam + audio" \
   "03" "Stream Desktop" \
   "04" "Stream Desktop + audio" \
   "05" "Alege alt dispozitiv de captura" \
   "06" "Paraseste programul"  2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`
  
  case "$selectat" in
    01) echo devv $dev #debug
	video_in="-v verbose -r 10 -s $cam_web -f video4linux2 -i /dev/$dev http://localhost:9003/webcam.ffm"
	audio_in=""
      	audio_out=""
	$stream_server -f $locatia/stream.conf & \
	$procesare  $video_in ;;
    02) echo "TO DO" ;;
    03) 
	video_in="-v verbose -r 10 -f x11grab -r 25 -s $desktop -i :0.0 http://localhost:9003/webcam.ffm"
	audio_in=""
      	audio_out=""
	$stream_server -f $locatia/stream.conf & \
	$procesare  $video_in ;;
    04) echo "TO DO" ;;
    05) tempfile2=/tmp/capclitmp2
	trap "rm -f $tempfile2" 0 1 2 5 15
	dispozitive=`ls /dev|grep video|nl`
	$DIALOG  --title "Ferestre deschise" --clear \
                 --menu "Selectati fereastra dorita:" 20 80 10 $dispozitive 2> $tempfile2
	selectie3=$?
	dispozitiv_s=`cat $tempfile2`
	export dev=`ls /dev|grep video|sed -n "${dispozitiv_s}p"`
	echo dev $dev #debug
	;;
    06)  echo "Cuuui ma laasi?!! ( opt. $selectat )"
         echo "desktop=$desktop"
         echo "test_tty=$test_tty"
         echo "DIALOG=$DIALOG"
         exit 0 ;;

	  esac

  if [ "$selectie0" == "255" ]; then
   echo "Exit by ESC!"
   exit 0
  fi

done
